name: UltraFlagKeeper
main: net.samagames.ufk.UltraFlagKeeper
version: 1.0

depend: [SamaGamesAPI, SurvivalAPI]

load: STARTUP

author: Rigner
website: http://samagames.net/

commands:
    flag:
        description:
        usage: